apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-app        # â¬… deployment for stage
  labels:
    app: stage-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stage-app
  template:
    metadata:
      labels:
        app: stage-app
    spec:
      containers:
        - name: stage-app
          image: IMAGE
          ports:
            - containerPort: 80
