apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-app
  labels:
    app: prod-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
        - name: prod-app
          image: IMAGE
          ports:
            - containerPort: 80
