apiVersion: v1
kind: Service
metadata:
  name: k8s-service
spec:
  type: LoadBalancer   # You can change to NodePort if cluster is local
  selector:
    app: k8s-app
  ports:
  - port: 80
    targetPort: 80
